"use server"
import {revalidatePath} from "next/cache"
import {z} from "zod"
import {requireRole} from "@/lib/auth/server"
import {canManageHomework,getHomeworkErrorMessage,homeworkFormSchema,mapHomework,mapSubmission,reviewFormSchema,submissionFormSchema,toHomeworkPayload,validateHomeworkRelationships,type HomeworkViewModel,type SubmissionViewModel} from "@/lib/homework/model"
import {createHomework,createHomeworkSubmission,deleteHomework,getHomeworkEntry,getHomeworkReferences,getHomeworkStudentNames,getHomeworkSubmissions,reviewHomeworkSubmission,updateHomework} from "@/lib/supabase/queries"
import {getIndiaToday} from "@/lib/locale/india"
type HResult={ok:true;homework:HomeworkViewModel}|{ok:false;error:string};type SResult={ok:true;submission:SubmissionViewModel}|{ok:false;error:string};type DResult={ok:true}|{ok:false;error:string}
async function validate(input:unknown,user:Awaited<ReturnType<typeof requireRole>>){const p=homeworkFormSchema.safeParse(input);if(!p.success)return{ok:false as const,error:p.error.issues[0]?.message??"Invalid homework."};const refs=await getHomeworkReferences();if(!validateHomeworkRelationships(p.data,refs))return{ok:false as const,error:"The selected branch, course, batch, and teacher assignment do not belong together."};if(user.role==="teacher"&&p.data.teacherId!==user.id)return{ok:false as const,error:"Teachers may assign homework only as themselves."};if(!canManageHomework(user,{branchId:p.data.branchId,teacherId:p.data.teacherId}))return{ok:false as const,error:"You cannot manage homework in this branch."};return{ok:true as const,data:p.data,refs}}
async function view(row:Awaited<ReturnType<typeof getHomeworkEntry>>,refs:Awaited<ReturnType<typeof getHomeworkReferences>>,user:Awaited<ReturnType<typeof requireRole>>){const sr=await getHomeworkSubmissions();const names=await getHomeworkStudentNames([...new Set(sr.map(x=>x.student_id))]);return mapHomework(row,refs,sr.map(x=>mapSubmission(x,names)),user)}
export async function createHomeworkAction(input:unknown):Promise<HResult>{const user=await requireRole(["admin","branch_manager","teacher"]);try{const c=await validate(input,user);if(!c.ok)return c;const row=await createHomework(toHomeworkPayload(c.data));revalidatePath("/dashboard/homework");return{ok:true,homework:await view(row,c.refs,user)}}catch(e){return{ok:false,error:getHomeworkErrorMessage(e,"create this homework")}}}
export async function updateHomeworkAction(id:string,input:unknown):Promise<HResult>{const user=await requireRole(["admin","branch_manager","teacher"]);if(!z.string().uuid().safeParse(id).success)return{ok:false,error:"Invalid homework identifier."};try{const current=await getHomeworkEntry(id);if(!canManageHomework(user,{branchId:current.branch_id,teacherId:current.teacher_id}))return{ok:false,error:"You cannot edit this homework."};const c=await validate(input,user);if(!c.ok)return c;const row=await updateHomework(id,toHomeworkPayload(c.data));revalidatePath("/dashboard/homework");return{ok:true,homework:await view(row,c.refs,user)}}catch(e){return{ok:false,error:getHomeworkErrorMessage(e,"update this homework")}}}
export async function deleteHomeworkAction(id:string):Promise<DResult>{const user=await requireRole(["admin","branch_manager","teacher"]);if(!z.string().uuid().safeParse(id).success)return{ok:false,error:"Invalid homework identifier."};try{const row=await getHomeworkEntry(id);if(!canManageHomework(user,{branchId:row.branch_id,teacherId:row.teacher_id}))return{ok:false,error:"You cannot delete this homework."};await deleteHomework(id);revalidatePath("/dashboard/homework");return{ok:true}}catch(e){return{ok:false,error:getHomeworkErrorMessage(e,"delete this homework")}}}
export async function submitHomeworkAction(input:unknown):Promise<SResult>{const user=await requireRole(["student"]);const p=submissionFormSchema.safeParse(input);if(!p.success)return{ok:false,error:p.error.issues[0]?.message??"Invalid submission."};try{await getHomeworkEntry(p.data.homeworkId);const now=new Date();const row=await createHomeworkSubmission({homework_id:p.data.homeworkId,student_id:user.id,submission_content:p.data.content,submitted_at:now.toISOString(),submitted_date:getIndiaToday(now),status:"submitted"});revalidatePath("/dashboard/homework");return{ok:true,submission:mapSubmission(row,new Map([[user.id,user.fullName??user.email]]))}}catch(e){return{ok:false,error:getHomeworkErrorMessage(e,"submit this homework")}}}
export async function reviewHomeworkSubmissionAction(input:unknown):Promise<SResult>{const user=await requireRole(["admin","branch_manager","teacher"]);const p=reviewFormSchema.safeParse(input);if(!p.success)return{ok:false,error:p.error.issues[0]?.message??"Invalid review."};try{const visible=await getHomeworkSubmissions();const existing=visible.find(x=>x.id===p.data.submissionId);if(!existing)return{ok:false,error:"Submission not found."};const homework=await getHomeworkEntry(existing.homework_id);if(!canManageHomework(user,{branchId:homework.branch_id,teacherId:homework.teacher_id}))return{ok:false,error:"You cannot review this submission."};const row=await reviewHomeworkSubmission(p.data.submissionId,{status:"reviewed",marks:p.data.marks,teacher_feedback:p.data.feedback||null});const names=await getHomeworkStudentNames([row.student_id]);revalidatePath("/dashboard/homework");return{ok:true,submission:mapSubmission(row,names)}}catch(e){return{ok:false,error:getHomeworkErrorMessage(e,"review this submission")}}}
