"use client"
import {useMemo,useState,type ChangeEvent,type FormEvent} from "react"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {homeworkFormSchema,type HomeworkFormData,type HomeworkReferences,type HomeworkViewModel} from "@/lib/homework/model"
import type {AuthoritativeUser} from "@/lib/auth/permissions"
import {getIndiaToday} from "@/lib/locale/india"

export function HomeworkForm({initialData,references,user,onSubmit,busy,error}:{initialData:HomeworkViewModel|null;references:HomeworkReferences;user:AuthoritativeUser;onSubmit:(x:HomeworkFormData)=>void|Promise<void>;busy:boolean;error:string}){
 const teacher=user.role==="teacher";const branch=user.role==="admin"?(initialData?.branchId??references.branches[0]?.id??""):(user.branchId??"");const today=getIndiaToday()
 const [data,setData]=useState<HomeworkFormData>({title:initialData?.title??"",description:initialData?.description??"",branchId:branch,courseId:initialData?.courseId??"",batchId:initialData?.batchId??"",teacherId:teacher?user.id:(initialData?.teacherId??""),assignedDate:initialData?.assignedDate??today,dueDate:initialData?.dueDate??today});const[validation,setValidation]=useState("")
 const courses=useMemo(()=>references.courses.filter(x=>x.branchId===data.branchId&&(teacher?references.assignments.some(a=>a.teacherId===user.id&&a.courseId===x.id&&a.branchId===data.branchId):true)),[data.branchId,references,user.id,teacher]);const batches=references.batches.filter(x=>x.branchId===data.branchId&&x.courseId===data.courseId);const teachers=references.teachers.filter(x=>x.branchId===data.branchId&&references.assignments.some(a=>a.teacherId===x.id&&a.courseId===data.courseId&&a.branchId===data.branchId))
 const change=(e:ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>{const{name,value}=e.target;setData(x=>name==="branchId"?{...x,branchId:value,courseId:"",batchId:"",teacherId:teacher?user.id:""}:name==="courseId"?{...x,courseId:value,batchId:"",teacherId:teacher?user.id:""}:{...x,[name]:value});setValidation("")}
 const submit=async(e:FormEvent)=>{e.preventDefault();const p=homeworkFormSchema.safeParse(data);if(!p.success){setValidation(p.error.issues[0]?.message??"Check the homework details.");return}await onSubmit(p.data)}
 const field="w-full rounded-md border border-input bg-background px-3 py-2"
 return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{(validation||error)&&<p role="alert" className="sm:col-span-2 rounded bg-destructive/10 p-3 text-sm text-destructive">{validation||error}</p>}<label>Title *<Input name="title" value={data.title} onChange={change} maxLength={150}/></label><label>Branch *<select name="branchId" aria-label="Branch" className={field} value={data.branchId} onChange={change} disabled={busy||user.role!=="admin"||!!initialData}>{references.branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Course *<select name="courseId" aria-label="Course" className={field} value={data.courseId} onChange={change} disabled={busy}><option value="">Select course</option>{courses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Batch *<select name="batchId" aria-label="Batch" className={field} value={data.batchId} onChange={change} disabled={busy}><option value="">Select batch</option>{batches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Teacher *<select name="teacherId" aria-label="Teacher" className={field} value={data.teacherId} onChange={change} disabled={busy||teacher}><option value="">Select assigned teacher</option>{teacher&&<option value={user.id}>{user.fullName??user.email}</option>}{!teacher&&teachers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Assigned date *<Input name="assignedDate" type="date" value={data.assignedDate} onChange={change}/></label><label>Due date *<Input name="dueDate" type="date" value={data.dueDate} onChange={change}/></label><label className="sm:col-span-2">Description<textarea name="description" value={data.description} onChange={change} maxLength={5000} rows={4} className={field}/></label><Button className="sm:col-span-2" disabled={busy}>{busy?"Saving...":initialData?"Update Homework":"Create Homework"}</Button></form>
}
