"use client"
import {useMemo,useState} from "react"
import {Edit2,FileText,Plus,Trash2} from "lucide-react"
import {createHomeworkAction,deleteHomeworkAction,reviewHomeworkSubmissionAction,submitHomeworkAction,updateHomeworkAction} from "@/app/dashboard/homework/actions"
import {HomeworkForm} from "@/components/dashboard/homework-form"
import {Button} from "@/components/ui/button"
import {Card,CardContent} from "@/components/ui/card"
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog"
import {Input} from "@/components/ui/input"
import type {AuthoritativeUser} from "@/lib/auth/permissions"
import type {HomeworkFormData,HomeworkReferences,HomeworkViewModel,SubmissionViewModel} from "@/lib/homework/model"
import {formatIndianDate,formatIndianDateTime} from "@/lib/locale/india"

export function HomeworkClient({initialHomework,references,user}:{initialHomework:HomeworkViewModel[];references:HomeworkReferences;user:AuthoritativeUser}){
 const[rows,setRows]=useState(initialHomework),[open,setOpen]=useState(false),[editing,setEditing]=useState<HomeworkViewModel|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("");const canManage=user.role!=="student";const visible=useMemo(()=>rows.filter(x=>`${x.title} ${x.courseName} ${x.batchName}`.toLowerCase().includes(search.toLowerCase())),[rows,search])
 const save=async(x:HomeworkFormData)=>{setBusy(true);setError("");const r=editing?await updateHomeworkAction(editing.id,x):await createHomeworkAction(x);if(r.ok){setRows(v=>editing?v.map(y=>y.id===editing.id?r.homework:y):[r.homework,...v]);setOpen(false);setEditing(null)}else setError(r.error);setBusy(false)}
 const remove=async(x:HomeworkViewModel)=>{if(!window.confirm(`Delete homework “${x.title}”?`))return;setBusy(true);const r=await deleteHomeworkAction(x.id);if(r.ok)setRows(v=>v.filter(y=>y.id!==x.id));else setError(r.error);setBusy(false)}
 const replaceSubmission=(h:HomeworkViewModel,s:SubmissionViewModel)=>setRows(v=>v.map(x=>x.id!==h.id?x:{...x,submission:s,submissions:[...x.submissions.filter(y=>y.id!==s.id),s]}))
 const submit=async(h:HomeworkViewModel,content:string)=>{setBusy(true);setError("");const r=await submitHomeworkAction({homeworkId:h.id,content});if(r.ok)replaceSubmission(h,r.submission);else setError(r.error);setBusy(false)}
 const review=async(h:HomeworkViewModel,s:SubmissionViewModel,marks:string,feedback:string)=>{setBusy(true);setError("");const r=await reviewHomeworkSubmissionAction({submissionId:s.id,marks:marks===""?null:Number(marks),feedback});if(r.ok)replaceSubmission(h,r.submission);else setError(r.error);setBusy(false)}
 return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="flex items-center gap-2 text-3xl font-bold"><FileText className="text-primary"/>Homework</h1><p className="mt-1 text-muted-foreground">Assignments and student submissions</p></div>{canManage&&<Dialog open={open} onOpenChange={v=>{if(!busy){setOpen(v);if(!v){setEditing(null);setError("")}}}}><DialogTrigger asChild><Button onClick={()=>setEditing(null)}><Plus size={18}/>Assign Homework</Button></DialogTrigger><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{editing?"Edit Homework":"Assign Homework"}</DialogTitle><DialogDescription>Use real branch, course, batch, and teacher relationships.</DialogDescription></DialogHeader><HomeworkForm key={editing?.id??"new"} initialData={editing} references={references} user={user} onSubmit={save} busy={busy} error={error}/></DialogContent></Dialog>}</div>{error&&!open&&<p role="alert" className="rounded bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<Input aria-label="Search homework" placeholder="Search homework..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid gap-4">{visible.length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">No homework found</CardContent></Card>:visible.map(h=><Card key={h.id}><CardContent className="space-y-4 pt-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{h.title}</h2><p className="text-sm text-muted-foreground">{h.courseName} · {h.batchName} · {h.teacherName}</p><p className="text-sm">Assigned {formatIndianDate(h.assignedDate)} · Due {formatIndianDate(h.dueDate)}</p><p className="mt-2 whitespace-pre-wrap text-sm">{h.description||"No description"}</p></div>{canManage&&<div className="flex gap-2"><Button aria-label={`Edit ${h.title}`} variant="outline" size="sm" onClick={()=>{setEditing(h);setOpen(true);setError("")}}><Edit2 size={16}/></Button><Button aria-label={`Delete ${h.title}`} variant="destructive" size="sm" onClick={()=>remove(h)}><Trash2 size={16}/></Button></div>}</div>{user.role==="student"?<StudentSubmission homework={h} busy={busy} onSubmit={submit}/>:<SubmissionReviews homework={h} busy={busy} onReview={review}/>}</CardContent></Card>)}</div></div>
}
function StudentSubmission({homework,busy,onSubmit}:{homework:HomeworkViewModel;busy:boolean;onSubmit:(h:HomeworkViewModel,c:string)=>void}){const[content,setContent]=useState("");if(homework.submission)return <div className="rounded border p-3 text-sm"><b>Status:</b> {homework.submission.status} · {formatIndianDateTime(homework.submission.submittedAt)}{homework.submission.marks!==null&&<span> · Marks: {homework.submission.marks}</span>}{homework.submission.feedback&&<p className="mt-2">Feedback: {homework.submission.feedback}</p>}</div>;return <form onSubmit={e=>{e.preventDefault();onSubmit(homework,content)}} className="space-y-2"><label className="text-sm font-medium">Your submission<textarea aria-label={`Submission for ${homework.title}`} value={content} onChange={e=>setContent(e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2" rows={4} maxLength={10000}/></label><Button disabled={busy||!content.trim()}>Submit Homework</Button></form>}
function SubmissionReviews({homework,busy,onReview}:{homework:HomeworkViewModel;busy:boolean;onReview:(h:HomeworkViewModel,s:SubmissionViewModel,m:string,f:string)=>void}){return <div className="space-y-3"><h3 className="font-medium">Submissions ({homework.submissions.length})</h3>{homework.submissions.map(s=><Review key={s.id} homework={homework} submission={s} busy={busy} onReview={onReview}/>)}</div>}
function Review({homework,submission,busy,onReview}:{homework:HomeworkViewModel;submission:SubmissionViewModel;busy:boolean;onReview:(h:HomeworkViewModel,s:SubmissionViewModel,m:string,f:string)=>void}){const[marks,setMarks]=useState(submission.marks?.toString()??""),[feedback,setFeedback]=useState(submission.feedback);return <div className="rounded border p-3 text-sm"><b>{submission.studentName}</b> · {submission.status} · {formatIndianDateTime(submission.submittedAt)}<p className="my-2 whitespace-pre-wrap">{submission.content}</p><div className="grid gap-2 sm:grid-cols-[8rem_1fr_auto]"><Input aria-label={`Marks for ${submission.studentName}`} type="number" min="0" value={marks} onChange={e=>setMarks(e.target.value)} placeholder="Marks"/><Input aria-label={`Feedback for ${submission.studentName}`} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Teacher feedback"/><Button disabled={busy} onClick={()=>onReview(homework,submission,marks,feedback)}>Save Review</Button></div></div>}
