"use client"
import { useMemo, useState, type FormEvent } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import type { TeacherFormData, TeacherViewModel } from "@/lib/teachers/model"

export function TeacherForm({ initialData, branches, courses, onSubmit, isSubmitting, error, canChangeBranch = true }: { initialData?: TeacherViewModel | null; branches: { id: string; name: string }[]; courses: { id: string; name: string; branchId: string }[]; onSubmit: (data: TeacherFormData) => void; isSubmitting: boolean; error: string; canChangeBranch?: boolean }) {
  const [data, setData] = useState<TeacherFormData>(initialData ? { fullName: initialData.fullName, email: initialData.email, phone: initialData.phone, branchId: initialData.branchId, qualification: initialData.qualification, specialization: initialData.specialization, experienceYears: initialData.experienceYears, status: initialData.status, joiningDate: initialData.joiningDate, courseIds: initialData.courseIds } : { fullName: "", email: "", phone: "", branchId: branches[0]?.id ?? "", qualification: "", specialization: "", experienceYears: 0, status: "active", joiningDate: new Date().toISOString().slice(0, 10), courseIds: [] })
  const available = useMemo(() => courses.filter((course) => course.branchId === data.branchId), [courses, data.branchId])
  const set = (name: keyof TeacherFormData, value: string | number | string[]) => setData((current) => ({ ...current, [name]: value }))
  return <form onSubmit={(event: FormEvent) => { event.preventDefault(); onSubmit(data) }} className="space-y-4">
    <label className="block space-y-2 text-sm font-medium">Full Name *<Input value={data.fullName} onChange={(event) => set("fullName", event.target.value)} required disabled={isSubmitting} /></label>
    <label className="block space-y-2 text-sm font-medium">Email *<Input type="email" value={data.email} onChange={(event) => set("email", event.target.value)} required disabled={isSubmitting || !!initialData} /></label>
    <label className="block space-y-2 text-sm font-medium">Phone<Input value={data.phone} onChange={(event) => set("phone", event.target.value)} disabled={isSubmitting} /></label>
    <label className="block space-y-2 text-sm font-medium">Branch *<select className="w-full rounded-md border bg-background px-3 py-2" value={data.branchId} onChange={(event) => setData((current) => ({ ...current, branchId: event.target.value, courseIds: [] }))} required disabled={isSubmitting || !canChangeBranch || !!initialData}><option value="">Select a branch</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label>
    <div className="grid grid-cols-2 gap-4"><label className="space-y-2 text-sm font-medium">Qualification<Input value={data.qualification} onChange={(event) => set("qualification", event.target.value)} disabled={isSubmitting} /></label><label className="space-y-2 text-sm font-medium">Experience<Input type="number" min="0" max="100" value={data.experienceYears} onChange={(event) => set("experienceYears", Number(event.target.value))} disabled={isSubmitting} /></label></div>
    <label className="block space-y-2 text-sm font-medium">Specialization<Input value={data.specialization} onChange={(event) => set("specialization", event.target.value)} disabled={isSubmitting} /></label>
    <label className="block space-y-2 text-sm font-medium">Assigned Courses<select multiple size={3} className="w-full rounded-md border bg-background px-3 py-2" value={data.courseIds} onChange={(event) => set("courseIds", Array.from(event.target.selectedOptions, (option) => option.value))} disabled={isSubmitting}>{available.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</select><span className="block text-xs text-muted-foreground">Hold Ctrl/Cmd to select multiple courses.</span></label>
    <div className="grid grid-cols-2 gap-4"><label className="space-y-2 text-sm font-medium">Status<select className="w-full rounded-md border bg-background px-3 py-2" value={data.status} onChange={(event) => set("status", event.target.value)} disabled={isSubmitting}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label className="space-y-2 text-sm font-medium">Joining Date<Input type="date" value={data.joiningDate} onChange={(event) => set("joiningDate", event.target.value)} required disabled={isSubmitting} /></label></div>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="w-full" disabled={isSubmitting}>{isSubmitting ? "Saving..." : initialData ? "Update Teacher" : "Send Teacher Invitation"}</Button>
  </form>
}
