"use client"
import { useMemo, useState } from "react"
import { BookOpen, Edit2, Plus, UserMinus, Users } from "lucide-react"
import { archiveTeacherAction, provisionTeacherAction, updateTeacherAction } from "@/app/dashboard/teachers/actions"
import { TeacherForm } from "@/components/dashboard/teacher-form"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { filterTeachers, replaceTeacher, type TeacherFormData, type TeacherViewModel } from "@/lib/teachers/model"

export function TeachersClient({ initialTeachers, branches, courses, canProvision }: { initialTeachers: TeacherViewModel[]; branches: { id: string; name: string }[]; courses: { id: string; name: string; branchId: string }[]; canProvision: boolean }) {
  const [teachers, setTeachers] = useState(initialTeachers); const [search, setSearch] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<TeacherViewModel | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const filtered = useMemo(() => filterTeachers(teachers, search), [teachers, search])
  const submit = async (data: TeacherFormData) => { setBusy(true); setError(""); try { const result = editing ? await updateTeacherAction(editing.id, data) : await provisionTeacherAction(data); if (!result.ok) return setError(result.error); setTeachers((current) => editing ? replaceTeacher(current, result.teacher) : [result.teacher, ...current]); setOpen(false); setEditing(null) } catch { setError("Unable to save this teacher. Please try again.") } finally { setBusy(false) } }
  const archive = async (teacher: TeacherViewModel) => { if (!window.confirm(`Archive ${teacher.fullName}? Their Auth account is preserved.`)) return; setBusy(true); setError(""); try { const result = await archiveTeacherAction(teacher.id); if (!result.ok) return setError(result.error); setTeachers((current) => replaceTeacher(current, result.teacher)) } catch { setError("Unable to archive this teacher.") } finally { setBusy(false) } }
  const active = teachers.filter((teacher) => teacher.status === "active").length; const avg = teachers.length ? Math.floor(teachers.reduce((sum, teacher) => sum + teacher.experienceYears, 0) / teachers.length) : 0
  return <div className="space-y-6"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Teachers</h1><p className="mt-2 text-muted-foreground">Manage Auth-backed faculty and course assignments</p></div>{canProvision && <Dialog open={open} onOpenChange={(value) => { if (busy) return; setOpen(value); if (!value) { setEditing(null); setError("") } }}><DialogTrigger asChild><Button onClick={() => { setEditing(null); setError("") }} className="gap-2"><Plus size={20} />Add Teacher</Button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{editing ? "Edit Teacher" : "Invite New Teacher"}</DialogTitle><DialogDescription>{editing ? "Update faculty details and assignments." : "Send an Auth invitation and create the teacher profile."}</DialogDescription></DialogHeader><TeacherForm key={editing?.id ?? "new"} initialData={editing} branches={branches} courses={courses} onSubmit={submit} isSubmitting={busy} error={error} /></DialogContent></Dialog>}</div>
  {error && !open && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><div className="flex justify-between text-sm text-muted-foreground"><span>Total Teachers</span><Users size={20}/></div></CardHeader><CardContent><div className="text-2xl font-bold">{teachers.length}</div></CardContent></Card><Card><CardHeader className="pb-2"><div className="flex justify-between text-sm text-muted-foreground"><span>Active Teachers</span><BookOpen size={20}/></div></CardHeader><CardContent><div className="text-2xl font-bold">{active}</div></CardContent></Card><Card><CardHeader className="pb-2"><div className="flex justify-between text-sm text-muted-foreground"><span>Avg. Experience</span><Users size={20}/></div></CardHeader><CardContent><div className="text-2xl font-bold">{avg} yrs</div></CardContent></Card></div>
  <Card><CardHeader><Input placeholder="Search by name, email, specialization, or branch..." value={search} onChange={(event) => setSearch(event.target.value)} /></CardHeader><CardContent>{filtered.length===0?<div className="py-12 text-center text-muted-foreground">{teachers.length?"No teachers found":"No teachers have been provisioned"}</div>:<div className="space-y-3">{filtered.map((teacher)=><div key={teacher.id} className="rounded-lg border p-4 hover:bg-muted/50"><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-3"><h3 className="font-semibold">{teacher.fullName}</h3><span className={`rounded-full px-2 py-1 text-xs ${teacher.status==="active"?"bg-green-100 text-green-800":"bg-red-100 text-red-800"}`}>{teacher.status}</span></div><div className="mt-3 grid gap-2 text-sm md:grid-cols-4"><span>{teacher.email}</span><span>{teacher.phone||"No phone"}</span><span>{teacher.experienceYears} years</span><span>{teacher.branchName}</span></div><div className="mt-3 flex flex-wrap gap-2">{teacher.courseNames.length?teacher.courseNames.map((name)=><span key={name} className="rounded bg-primary/10 px-2 py-1 text-xs text-primary">{name}</span>):<span className="text-sm text-muted-foreground">No course assignments</span>}</div></div><div className="flex gap-2"><Dialog open={open&&editing?.id===teacher.id} onOpenChange={(value)=>{if(busy)return;setOpen(value);if(!value){setEditing(null);setError("")}}}><DialogTrigger asChild><Button variant="outline" size="sm" aria-label={`Edit ${teacher.fullName}`} onClick={()=>{setEditing(teacher);setError("");setOpen(true)}}><Edit2 size={16}/></Button></DialogTrigger><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Edit Teacher</DialogTitle><DialogDescription>Update faculty details and assignments.</DialogDescription></DialogHeader><TeacherForm key={teacher.id} initialData={teacher} branches={branches} courses={courses} onSubmit={submit} isSubmitting={busy} error={error} canChangeBranch={canProvision}/></DialogContent></Dialog><Button variant="destructive" size="sm" aria-label={`Archive ${teacher.fullName}`} disabled={busy||teacher.status==="inactive"} onClick={()=>archive(teacher)}><UserMinus size={16}/></Button></div></div></div>)}</div>}</CardContent></Card></div>
}
