"use client"
import { useMemo, useState } from "react"
import { Edit2, Mail, Plus } from "lucide-react"
import { provisionUserAction, updateUserAction } from "@/app/dashboard/users/actions"
import { UserForm } from "@/components/dashboard/user-form"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { filterUsers, replaceUser, type UserFormData, type UserViewModel } from "@/lib/users/model"

const labels = { admin: "Admin", branch_manager: "Branch Manager", teacher: "Teacher", student: "Student" }
const colors = { admin: "bg-red-100 text-red-800", branch_manager: "bg-blue-100 text-blue-800", teacher: "bg-green-100 text-green-800", student: "bg-purple-100 text-purple-800" }
export function UsersClient({ actorId, initialUsers, branches }: { actorId: string; initialUsers: UserViewModel[]; branches: { id: string; name: string }[] }) {
  const [users, setUsers] = useState(initialUsers); const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<UserViewModel | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const filtered = useMemo(() => filterUsers(users, search, role), [users, search, role])
  const submit = async (data: UserFormData) => { setBusy(true); setError(""); try { const result = editing ? await updateUserAction(editing.id, data) : await provisionUserAction(data); if (!result.ok) return setError(result.error); setUsers((current) => editing ? replaceUser(current, result.user) : [result.user, ...current]); if ("invitationSent" in result && result.invitationSent === false) setError("User created, but the email rate limit prevented delivery. Resend the invitation from Supabase Auth later."); setOpen(false); setEditing(null) } catch { setError("Unable to save this user. Please try again.") } finally { setBusy(false) } }
  return <div className="space-y-6"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Users</h1><p className="mt-2 text-muted-foreground">Manage real Auth-backed profiles and permissions</p></div><Dialog open={open} onOpenChange={(value) => { if (busy) return; setOpen(value); if (!value) { setEditing(null); setError("") } }}><DialogTrigger asChild><Button onClick={() => { setEditing(null); setError("") }} className="gap-2"><Plus size={20} />Add User</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{editing ? "Edit User" : "Invite New User"}</DialogTitle><DialogDescription>{editing ? "Update authoritative profile access." : "Send a Supabase Auth invitation and configure the profile."}</DialogDescription></DialogHeader><UserForm key={editing?.id ?? "new"} initialData={editing} branches={branches} onSubmit={submit} isSubmitting={busy} error={error} /></DialogContent></Dialog></div>
  {error && !open && <p role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
  <Card><CardHeader><div className="flex flex-col gap-4 md:flex-row"><Input className="flex-1" placeholder="Search by name, email, or branch..." value={search} onChange={(event) => setSearch(event.target.value)} /><select className="rounded-md border bg-background px-3 py-2" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All Roles</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></CardHeader><CardContent>{filtered.length === 0 ? <div className="py-12 text-center text-muted-foreground">{users.length ? "No users found" : "No profiles found"}</div> : <div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b"><th className="px-4 py-3 text-left">Name</th><th className="px-4 py-3 text-left">Email</th><th className="px-4 py-3 text-left">Role</th><th className="px-4 py-3 text-left">Branch</th><th className="px-4 py-3 text-left">Status</th><th className="px-4 py-3 text-left">Actions</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-b hover:bg-muted/50"><td className="px-4 py-3">{user.fullName}</td><td className="px-4 py-3"><span className="flex items-center gap-2"><Mail size={16} />{user.email}</span></td><td className="px-4 py-3"><span className={`rounded-full px-3 py-1 text-xs font-medium ${colors[user.role]}`}>{labels[user.role]}</span></td><td className="px-4 py-3">{user.branchName}</td><td className="px-4 py-3">{user.status}</td><td className="px-4 py-3"><Button variant="outline" size="sm" aria-label={`Edit ${user.fullName}`} disabled={busy || user.id === actorId} onClick={() => { setEditing(user); setError(""); setOpen(true) }}><Edit2 size={16} /></Button></td></tr>)}</tbody></table></div>}</CardContent></Card></div>
}
