import {z} from "zod"
export const assessmentFormSchema=z.object({studentId:z.string().uuid(),courseId:z.string().uuid(),batchId:z.string().uuid(),teacherId:z.string().uuid(),branchId:z.string().uuid(),testName:z.string().trim().min(1).max(200),subject:z.string().trim().min(1).max(200),marksObtained:z.coerce.number().min(0),totalMarks:z.coerce.number().positive(),testDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),notes:z.string().trim().max(2000)}).refine(x=>x.marksObtained<=x.totalMarks,{message:"Marks obtained cannot exceed total marks.",path:["marksObtained"]})
export type AssessmentFormData=z.infer<typeof assessmentFormSchema>
export const assessmentRowSchema=z.object({id:z.string().uuid(),student_id:z.string().uuid(),course_id:z.string().uuid(),batch_id:z.string().uuid(),teacher_id:z.string().uuid().nullable(),branch_id:z.string().uuid(),test_name:z.string(),subject:z.string().nullable(),marks_obtained:z.coerce.number(),total_marks:z.coerce.number(),percentage:z.coerce.number().nullable(),grade:z.string().nullable(),test_date:z.string(),notes:z.string().nullable(),created_at:z.string().nullable(),updated_at:z.string().nullable()})
export type AssessmentRow=z.infer<typeof assessmentRowSchema>
export type AssessmentView=AssessmentFormData&{id:string;studentName:string;courseName:string;batchName:string;teacherName:string;percentage:number;grade:string}
export type AssessmentRefs={branches:{id:string;name:string}[];courses:{id:string;name:string;branchId:string}[];batches:{id:string;name:string;courseId:string;branchId:string}[];teachers:{id:string;name:string;branchId:string}[];students:{id:string;name:string;branchId:string;courseId:string;batchId:string}[]}
export const gradeFor=(p:number)=>p>=90?"A":p>=80?"B":p>=70?"C":p>=60?"D":"F"
export function mapAssessment(r:AssessmentRow,refs:AssessmentRefs):AssessmentView{return{id:r.id,studentId:r.student_id,courseId:r.course_id,batchId:r.batch_id,teacherId:r.teacher_id??"",branchId:r.branch_id,testName:r.test_name,subject:r.subject??"",marksObtained:r.marks_obtained,totalMarks:r.total_marks,testDate:r.test_date,notes:r.notes??"",percentage:r.percentage??Math.round(r.marks_obtained/r.total_marks*10000)/100,grade:r.grade??gradeFor(r.percentage??0),studentName:refs.students.find(x=>x.id===r.student_id)?.name??"Student",courseName:refs.courses.find(x=>x.id===r.course_id)?.name??"Course",batchName:refs.batches.find(x=>x.id===r.batch_id)?.name??"Batch",teacherName:refs.teachers.find(x=>x.id===r.teacher_id)?.name??"Teacher"}}
