import { readFileSync } from "node:fs"
import { describe,expect,it } from "vitest"
const sql=readFileSync("scripts/015_teachers_users_phase2.sql","utf8").toLowerCase(), normalized=sql.replace(/\s+/g," ")
const actions=[readFileSync("app/dashboard/users/actions.ts","utf8"),readFileSync("app/dashboard/teachers/actions.ts","utf8")].join("\n")
describe("Phase 2D security guardrails",()=>{
  it("is transactional, repeatable, RLS-enabled, and non-cascading",()=>{expect(normalized).toContain("begin;");expect(normalized.trim().endsWith("commit;")).toBe(true);expect(sql).toContain("create table if not exists public.teacher_details");expect(sql).toContain("create table if not exists public.teacher_course_assignments");expect(sql).toContain("drop policy if exists");expect(sql).toContain("enable row level security");expect(sql).not.toContain("on delete cascade")})
  it("enforces teacher role and branch-consistent assignments",()=>{expect(normalized).toContain("p.role='teacher' and p.branch_id=branch_id");expect(normalized).toContain("c.id=course_id and c.branch_id=branch_id");expect(sql).toContain("foreign key (teacher_id, branch_id)");expect(sql).toContain("foreign key (course_id, branch_id)")})
  it("keeps role, branch, and status self-promotion blocked",()=>{expect(normalized).toContain("role=public.current_user_role()");expect(normalized).toContain("branch_id is not distinct from public.current_user_branch_id()");expect(normalized).toContain("status=public.current_user_profile_status()");expect(normalized).not.toContain("grant update (email,")})
  it("scopes branch managers and denies anonymous access",()=>{expect(normalized).toContain("current_user_role()='branch_manager' and branch_id=public.current_user_branch_id()");expect(normalized).toContain("revoke all on public.teacher_details, public.teacher_course_assignments from anon")})
  it("requires authoritative server roles for provisioning and management",()=>{expect(actions.match(/requireRole\(\["admin"\]\)/g)?.length).toBeGreaterThanOrEqual(2);expect(actions).toContain('requireRole(["admin","branch_manager"])');expect(actions).toContain("deleteUser(createdId)")})
  it("keeps the service key server-only and public signup student-only",()=>{expect(readFileSync("lib/supabase/admin.ts","utf8")).toContain('import "server-only"');expect(readFileSync("lib/env.ts","utf8")).toContain("SUPABASE_SERVICE_ROLE_KEY");expect(readFileSync("lib/env.ts","utf8")).not.toContain("NEXT_PUBLIC_SUPABASE_SERVICE");expect(normalized).toContain("'student'");expect(normalized).not.toMatch(/raw_user_meta_data\s*->>\s*'role'/)})
  it("handles provider email throttling without exposing invite links",()=>{const admin=readFileSync("lib/supabase/admin.ts","utf8");expect(admin).toContain('over_email_send_rate_limit');expect(admin).toContain('type: "invite"');expect(admin).not.toMatch(/console\.(log|error)/)})
  it("provides an invite acceptance session bootstrap",()=>{const invite=readFileSync("app/auth/invite/page.tsx","utf8");expect(invite).toContain("supabase.auth.setSession");expect(invite).toContain("exchangeCodeForSession");expect(invite).toContain('window.history.replaceState({}, "", "/auth/invite")')})
})
