import { z } from "zod"
import type { AuthoritativeUser } from "@/lib/auth/permissions"

const uuid=z.string().uuid()
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/)
export const homeworkDatabaseRowSchema=z.object({id:uuid,title:z.string(),description:z.string().nullable(),course_id:uuid,batch_id:uuid,teacher_id:uuid,assigned_date:date,due_date:date,branch_id:uuid,created_at:z.string().nullable(),updated_at:z.string().nullable()})
export const submissionDatabaseRowSchema=z.object({id:uuid,homework_id:uuid,student_id:uuid,submitted_date:date.nullable(),submitted_at:z.string().nullable(),submission_content:z.string().nullable(),status:z.enum(["submitted","late","reviewed"]),marks:z.number().int().nonnegative().nullable(),teacher_feedback:z.string().nullable(),created_at:z.string().nullable(),updated_at:z.string().nullable()})
export const homeworkFormSchema=z.object({title:z.string().trim().min(2).max(150),description:z.string().trim().max(5000),branchId:uuid,courseId:uuid,batchId:uuid,teacherId:uuid,assignedDate:date,dueDate:date}).refine(x=>x.dueDate>=x.assignedDate,{message:"Due date must be on or after the assigned date.",path:["dueDate"]})
export const submissionFormSchema=z.object({homeworkId:uuid,content:z.string().trim().min(1,"Submission content is required.").max(10000)})
export const reviewFormSchema=z.object({submissionId:uuid,marks:z.coerce.number().int().min(0).nullable(),feedback:z.string().trim().max(5000)})

export type HomeworkDatabaseRow=z.infer<typeof homeworkDatabaseRowSchema>
export type HomeworkFormData=z.infer<typeof homeworkFormSchema>
export type HomeworkCreatePayload={title:string;description:string|null;branch_id:string;course_id:string;batch_id:string;teacher_id:string;assigned_date:string;due_date:string}
export type HomeworkUpdatePayload=HomeworkCreatePayload
export type SubmissionDatabaseRow=z.infer<typeof submissionDatabaseRowSchema>
export type SubmissionCreatePayload={homework_id:string;student_id:string;submission_content:string;submitted_date:string;submitted_at:string;status:"submitted"|"late"}
export type SubmissionReviewPayload={status:"reviewed";marks:number|null;teacher_feedback:string|null}
export interface HomeworkReferences{branches:{id:string;name:string}[];courses:{id:string;name:string;branchId:string}[];batches:{id:string;name:string;courseId:string;branchId:string}[];teachers:{id:string;name:string;branchId:string}[];assignments:{teacherId:string;courseId:string;branchId:string}[]}
export interface SubmissionViewModel{id:string;homeworkId:string;studentId:string;studentName:string;submittedAt:string|null;content:string;status:"submitted"|"late"|"reviewed";marks:number|null;feedback:string}
export interface HomeworkViewModel extends HomeworkFormData{id:string;branchName:string;courseName:string;batchName:string;teacherName:string;createdAt:string|null;updatedAt:string|null;submission:SubmissionViewModel|null;submissions:SubmissionViewModel[]}

export function toHomeworkPayload(x:HomeworkFormData):HomeworkCreatePayload{const v=homeworkFormSchema.parse(x);return{title:v.title,description:v.description||null,branch_id:v.branchId,course_id:v.courseId,batch_id:v.batchId,teacher_id:v.teacherId,assigned_date:v.assignedDate,due_date:v.dueDate}}
export function validateHomeworkRelationships(x:HomeworkFormData,r:HomeworkReferences){return r.courses.some(c=>c.id===x.courseId&&c.branchId===x.branchId)&&r.batches.some(b=>b.id===x.batchId&&b.courseId===x.courseId&&b.branchId===x.branchId)&&r.teachers.some(t=>t.id===x.teacherId&&t.branchId===x.branchId)&&r.assignments.some(a=>a.teacherId===x.teacherId&&a.courseId===x.courseId&&a.branchId===x.branchId)}
export function canManageHomework(user:AuthoritativeUser,row:{branchId:string;teacherId:string}){return user.role==="admin"||(user.role==="branch_manager"&&user.branchId===row.branchId)||(user.role==="teacher"&&user.id===row.teacherId&&user.branchId===row.branchId)}
export function mapSubmission(row:SubmissionDatabaseRow,names:Map<string,string>):SubmissionViewModel{return{id:row.id,homeworkId:row.homework_id,studentId:row.student_id,studentName:names.get(row.student_id)??"Student",submittedAt:row.submitted_at,content:row.submission_content??"",status:row.status,marks:row.marks,feedback:row.teacher_feedback??""}}
export function mapHomework(row:HomeworkDatabaseRow,refs:HomeworkReferences,submissions:SubmissionViewModel[],user:AuthoritativeUser):HomeworkViewModel{return{id:row.id,title:row.title,description:row.description??"",branchId:row.branch_id,courseId:row.course_id,batchId:row.batch_id,teacherId:row.teacher_id,assignedDate:row.assigned_date,dueDate:row.due_date,branchName:refs.branches.find(x=>x.id===row.branch_id)?.name??"Unknown branch",courseName:refs.courses.find(x=>x.id===row.course_id)?.name??"Unknown course",batchName:refs.batches.find(x=>x.id===row.batch_id)?.name??"Unknown batch",teacherName:refs.teachers.find(x=>x.id===row.teacher_id)?.name??"Assigned teacher",createdAt:row.created_at,updatedAt:row.updated_at,submission:submissions.find(x=>x.homeworkId===row.id&&x.studentId===user.id)??null,submissions:submissions.filter(x=>x.homeworkId===row.id)}}
export function getHomeworkErrorMessage(error:unknown,operation:string){const e=typeof error==="object"&&error?error as{code?:string;message?:string}:{};if(e.message?.includes("homework_has_submissions")||e.code==="23503")return "This homework cannot be deleted because student submissions exist.";if(e.message?.includes("homework_teacher_assignment_invalid"))return "The selected teacher is not actively assigned to this course.";if(e.message?.includes("homework_student_not_eligible"))return "You are not actively enrolled in this homework's branch, course, and batch.";if(e.code==="23505")return "You have already submitted this homework.";if(e.code==="42501")return "You do not have permission to perform this action.";return `We could not ${operation}. Please try again.`}
