import {describe,expect,it} from "vitest"
import {canManageHomework,homeworkFormSchema,mapHomework,mapSubmission,toHomeworkPayload,validateHomeworkRelationships,type HomeworkReferences} from "../../lib/homework/model"

const id={branch:"11111111-1111-4111-8111-111111111111",course:"22222222-2222-4222-8222-222222222222",batch:"33333333-3333-4333-8333-333333333333",teacher:"44444444-4444-4444-8444-444444444444",student:"55555555-5555-4555-8555-555555555555",row:"66666666-6666-4666-8666-666666666666"}
const refs:HomeworkReferences={branches:[{id:id.branch,name:"Pune"}],courses:[{id:id.course,name:"Math",branchId:id.branch}],batches:[{id:id.batch,name:"Morning",courseId:id.course,branchId:id.branch}],teachers:[{id:id.teacher,name:"Asha",branchId:id.branch}],assignments:[{teacherId:id.teacher,courseId:id.course,branchId:id.branch}]}
const form={title:"Algebra",description:"Solve exercises",branchId:id.branch,courseId:id.course,batchId:id.batch,teacherId:id.teacher,assignedDate:"2026-09-18",dueDate:"2026-09-20"}
describe("Homework model",()=>{
 it("validates and maps create payload",()=>expect(toHomeworkPayload(form)).toEqual({title:"Algebra",description:"Solve exercises",branch_id:id.branch,course_id:id.course,batch_id:id.batch,teacher_id:id.teacher,assigned_date:"2026-09-18",due_date:"2026-09-20"}))
 it("rejects due dates before assignment",()=>expect(homeworkFormSchema.safeParse({...form,dueDate:"2026-09-17"}).success).toBe(false))
 it("validates branch/course/batch/teacher assignment consistency",()=>{expect(validateHomeworkRelationships(form,refs)).toBe(true);expect(validateHomeworkRelationships({...form,batchId:id.row},refs)).toBe(false);expect(validateHomeworkRelationships(form,{...refs,assignments:[]})).toBe(false)})
 it("authorizes staff with correct scope",()=>{expect(canManageHomework({id:id.row,email:"a",role:"admin",branchId:null,fullName:null,status:"active"},{branchId:id.branch,teacherId:id.teacher})).toBe(true);expect(canManageHomework({id:id.teacher,email:"t",role:"teacher",branchId:id.branch,fullName:null,status:"active"},{branchId:id.branch,teacherId:id.teacher})).toBe(true);expect(canManageHomework({id:id.row,email:"t",role:"teacher",branchId:id.branch,fullName:null,status:"active"},{branchId:id.branch,teacherId:id.teacher})).toBe(false)})
 it("maps submissions and homework without persisting names",()=>{const s=mapSubmission({id:id.row,homework_id:id.row,student_id:id.student,submitted_date:"2026-09-19",submitted_at:"2026-09-19T00:00:00Z",submission_content:"Answer",status:"submitted",marks:null,teacher_feedback:null,created_at:null,updated_at:null},new Map([[id.student,"Student"]]));expect(mapHomework({id:id.row,title:"Algebra",description:null,course_id:id.course,batch_id:id.batch,teacher_id:id.teacher,assigned_date:"2026-09-18",due_date:"2026-09-20",branch_id:id.branch,created_at:null,updated_at:null},refs,[s],{id:id.student,email:"s",role:"student",branchId:id.branch,fullName:null,status:"active"}).submission?.content).toBe("Answer")})
})
